name: mod-build
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/The-Aether-Team/The-Aether/archive/refs/heads/1.16.zip
      Pack_Name: 1.16
      Open_Pack_Name: The-Aether-1.16
    steps:
    - uses: actions/checkout@v2
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
