name: mod-build
on: 
  #push:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/PssbleTrngle/CreateDeco/archive/refs/heads/1.18-main.zip
      Pack_Name: 1.18-main
      Open_Pack_Name: CreateDeco-1.18-main
    steps:
    - uses: actions/checkout@v2
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
