name: mod-build
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/TeamGalacticraft/Galacticraft/archive/refs/heads/minecraft/1.19.4.zip
      Pack_Name: 1.19.4
      Open_Pack_Name: Galacticraft-minecraft-1.19.4
    steps:
    - uses: actions/checkout@v2
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
