name: mod-build
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/Thorfusion/Mekanism-Community-Edition/archive/refs/heads/1.7.10.zip
      Pack_Name: 1.7.10
      Open_Pack_Name: Mekanism-Community-Edition-1.7.10
    steps:
    - uses: actions/checkout@v2
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: ${{ env.Open_Pack_Name }}
        path: /opt/libs/
