name: mod-build
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/xemnes/twilightforest/archive/refs/heads/1.12.x-door_fix+misc.zip
      Pack_Name: 1.12.x-door_fix+misc
      Open_Pack_Name: twilightforest-1.12.x-door_fix-misc
    steps:
    - uses: actions/checkout@v2
    - run: 
        sh ./start.sh
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
